package com.nt.beans;

import org.springframework.beans.factory.annotation.Lookup;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


	
@Component("container")
@Scope("singleton")
public interface WebContainer{
	
	//@Lookup //altenative to <lookup-method>
	@Lookup("handler")
	public abstract RequestHandler createRequestHandler();
	default   void  processRequest(String data) {
		
		RequestHandler handler=null;
		
		System.out.println("WebContainer is processing request with data::"+ data + "by giving it to handler");
		//get depedent object using depedency lookup code generated by container
		handler=createRequestHandler();
		//use depedent object
		handler.handleRequest(data);
		
	}

}

